apiVersion: v1
kind: Service
metadata:
  name: hello-node-service
spec:
  type: NodePort
  selector:
    app: hello-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007